name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  BACKEND_PROJECT_PATH: "./whobought-backend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      
      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.BACKEND_PROJECT_PATH }}/whobought-backend.csproj
          dotnet restore ./infrastructure/WhoBoughtInfra.csproj
      
      - name: Build
        run: dotnet build ${{ env.BACKEND_PROJECT_PATH }}/whobought-backend.csproj --configuration Release --no-restore
      
      - name: Publish .NET App
        run: dotnet publish ${{ env.BACKEND_PROJECT_PATH }}/whobought-backend.csproj -c Release -o ./publish
      
      - name: Create deployment package
        run: |
          cd ./publish
          zip -r ../whobought-api.zip .
          cd ..
      
      - name: Configure Azure credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy infrastructure
        run: |
          cd ./infrastructure
          pulumi login
          pulumi stack select dev --create
          pulumi up --yes
      
      - name: Get App Service name
        id: get_app
        run: |
          cd ./infrastructure
          APP_NAME=$(pulumi stack output appServiceName)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_OUTPUT
      
      - name: Deploy application to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.get_app.outputs.APP_NAME }}
          package: ./whobought-api.zip 